### ISSUE TITLE
GG movie recorded in 2.3.0 not recognised in dev build

### ISSUE THREAD

**Issue by Glitcholog** [TASVideos/BizHawk#1297]
Title say it all, pressing the start button (required by many games) cause the game to either freeze or reset, making most game unplayable on the latest version of Bizhawk. Sega Game Gear system

**Comment by synnae** [comment]
Confirmed it does happen on my end as well. If anyone needs a couple examples, there's Moldorian and Nazo Puyo Arle no Roux. Pressing start on them (which is required to begin the game), causes them to reset.

**Comment by Asnivor** [comment]
Confirmed in 2.3.0.

However this appears to have been fixed in the Dev version. This may or may not be the fix commit: 
 https://github.com/TASVideos/BizHawk/commit/7767ed6fb9113d49354ec1255c52efe3518ed27e

Latest dev version is always here:
https://ci.appveyor.com/project/zeromus/bizhawk-udexo/build/artifacts

Problem does not occur for me in the latest dev version - for the two mentioned games above anyway.

Please test with dev and let us know if this can now be closed.

**Comment by Glitcholog** [comment]
With the dev version , many games were now working correctly, but there are game that worked in 2.2.2 that are still broken in 2.3.0 and the dev version

Bugs Bunny in Double Trouble (USA, Europe)
Double Dragon (USA, Europe)
Phantom 2040 (USA, Europe)
TaleSpin (USA, Europe)
5 in 1 Funpak (USA) (Doesn't require Start to play the game, but pressing it reset, maybe it is intentional to choose the games)
Chessmaster, The (USA, Europe)

**Comment by Asnivor** [comment]
I'll take a look a bit later

**Comment by Glitcholog** [comment]
I just tried again and that all those title work (beside double dragon being badly glitched). So I probably took 2.3 instead of DEV when I retried

**Comment by Glitcholog** [comment]
although a separate problem, the dev version cannot resgonize game gear movie file because its say it should be SMS (in previous version, the movie file was considered a SMS file, regardless of if it is a game gear game or not

**Comment by Asnivor** [comment]
This is due to a requested change made here: https://github.com/TASVideos/BizHawk/pull/1277

I guess we either need to handle this properly somehow. Editing the header file inside the .bk2 and changing 'SMS' to 'GG' should work, so its probably trivial enough to handle inside bizhawk. I'll take a look when I have time.

**Comment by Glitcholog** [comment]
Can confirm that changing the Platform back to SMS  in header.txt via 7zip and a text editor will allow the movie to be played by the dev version and recorded with AVI

**Comment by synnae** [comment]
Tested Moldorian and the Nazo Puyo game in the latest dev build and they now work fine. Thanks for the fix.

Sorry for not replying earlier, I only managed to look at stuff now.

**Comment by vadosnaprimer** [comment]
This is no longer relevant, as commits causing this were reverted.
