### ISSUE TITLE
[NesHawk] Small list of bugged games

### ISSUE THREAD

**Issue by Sonia-7** [TASVideos/BizHawk#1757]
Tested in the latest stable version (2.3.2), NesHawk core. The following games have issues:

**Bubble Bobble 2 (Japan)
sha1:93289C300488B69F959EB08AD075965DCC3EF2F3
md5:60454A2425152E7BAC6B2411A2386EBF**

**Captain Saver (Japan)
sha1:685886553C8858B704D90456F2E8F52003352598
md5:329C1026063BCD496714DEABE091AF91**

**Jetsons, The - Cogswell's Caper (Japan)
sha1:127B2C71AB249ECC197F7F88CEFC1FDE2EC7F2CE
md5:16EE244AC9BA24651878FA9B835353AD**

Garbage graphics in all of them. Here are some screenshots:

![Bubble Bobble 2 (Japan)_BizHawk](https://user-images.githubusercontent.com/24638400/70739669-223a4c80-1cf6-11ea-9831-1f60a172cb7d.png) 
![Captain Saver (Japan)_BizHawk](https://user-images.githubusercontent.com/24638400/70739689-2bc3b480-1cf6-11ea-9a22-e1a77f36f579.png) 
![Jetsons, The - Cogswell's Caper! (Japan)_BizHawk](https://user-images.githubusercontent.com/24638400/70739807-73e2d700-1cf6-11ea-977a-baed4341691b.png)

One thing in common shared between them is the INES Mapper 033 (Taito), so it may be buggy emulation of that mapper. Mesen emulates them correctly:

![Bubble Bobble 2 (Japan)_Mesen](https://user-images.githubusercontent.com/24638400/70740164-506c5c00-1cf7-11ea-9aa9-d7213cb017b9.png)
![Captain Saver (Japan)_Mesen](https://user-images.githubusercontent.com/24638400/70740166-53674c80-1cf7-11ea-9c71-6c50a23e29ca.png)
![Jetsons, The - Cogswell's Caper! (Japan)_Mesen](https://user-images.githubusercontent.com/24638400/70740172-55c9a680-1cf7-11ea-94ce-3377982ffb31.png)

Worth mentioning that their (USA) versions work fine in NesHawk, most likely because the mapper was changed to MMC3.
______________________________________________________________________________________________________

**Klax (Japan)
sha1:BF67BD47C855DFFD26D1CB1A37A0A4FE1B6AFA27
md5:4DF1157321FC2AAC0A35725B455E56A0**

Screen shakes constantly during gameplay:

First frame / next frame
![Klax (Japan)_1](https://user-images.githubusercontent.com/24638400/70741883-1d2bcc00-1cfb-11ea-8f9d-268e2ef52413.png) ![Klax (Japan)_2](https://user-images.githubusercontent.com/24638400/70741887-2026bc80-1cfb-11ea-83a4-d2f7889470a8.png)
______________________________________________________________________________________________________

**Artelius (Japan)
sha1:84BEF49E92897D4FCB4CA2C2103B7522D624B304
md5:41E5902E4417444F689468EAD4865714**

This is a weird one. The room's collision detection is shifted to the right from where the graphics are. Basically, things are happening one tile to the right from where they appear to be.

![Artelius (Japan)](https://user-images.githubusercontent.com/24638400/70742166-aa6f2080-1cfb-11ea-9312-2ce8fa027653.png)

Here's a save state with the bug reproduced:
[Artelius bug.zip](https://github.com/TASVideos/BizHawk/files/3957477/Artelius.bug.zip)

Note that if you reboot the core and start the game over, everything works normally, so I don't know how exactly I activated that bug. Not sure if that was caused by bad emulation or if it's just a bug in the game itself.

**Comment by YoshiRulz** [comment]
see also https://github.com/TASVideos/BizHawk/issues/860#issuecomment-348698182

**Comment by alyosha-tas** [comment]
Artelius happens with U/D L/R simultaneously. The game doesn't expect it to happen, not an emulation issue as far as I can tell.

**Comment by Yave-Yu** [comment]
Karnov (Japan)
Status bar glitch

**Comment by Sonia-7** [comment]
Here's another one. **Saint Seiya Ougon Densetsu**'s title screen is broken:

![SS1](https://user-images.githubusercontent.com/24638400/102294322-d4b77780-3f27-11eb-8b91-35b3478f3749.png)

Funny thing is that even FCEUX does it right:

![SS2](https://user-images.githubusercontent.com/24638400/102294342-e0a33980-3f27-11eb-86c4-018fef0da697.png)

By the way, It's been 1 year since this thread was open and those bugs remain unfixed. The games run flawlessly in Nestopia, puNES and Mesen.

If this is never going to be fixed, then maybe it'd be better to take the PCE approach and implement an external, more accurate core, while still leaving the in-house one as an option. Mesen would be the best candidate since it's now a "frozen" emulator. According to its developer, 0.9.9 is the last and it will no longer be updated. (Not counting the community project that may come out of it.)

**Comment by alyosha-tas** [comment]
Saint Seiya mapper fixed. Jetsons, Bubble Bobble 2, and Captain Saver now also sent to correct mapper 

Haven't looked at karnov or klax yet

**Comment by alyosha-tas** [comment]
Klax is fixed, this was one of those 'when 2 things happen simultaneously what's supposed to happen' situations. A counter clear and an IRQ clock happened at near the same time. For Klax to work, the clear must happen a little later.

Might also fix Karnov, but haven't checked.

**Comment by alyosha-tas** [comment]
I didn't see any problems with Karnov as long as the correct mapper is applied. I added a game DB entry just in case any ROMs out there mistakenly label it as MMC3.

I think that was the last issue here, closing.

**Comment by Sonia-7** [comment]
Jetsons is still not fixed. If you wait a little on the title screen, a sequence introducing the game's cast will happen. There are garbled graphics in it:

![Jetsons, The - Cogswell's Caper](https://user-images.githubusercontent.com/24638400/134544572-c5097369-c6c7-4435-963e-3c4e6d88e2b2.png)

**Comment by alyosha-tas** [comment]
Hmm, ok I'll add it to the other list of NESHawk bugged games, thanks for the report.
