### ISSUE TITLE
[melonDS] Crash when Set Customization for firmware.bin

### ISSUE THREAD

**Issue by Real96** [TASVideos/BizHawk#1922]
When you start a new clean install of Bizhawk and try to Set Customization for firmware.bin, app crashes giving this error: https://pastebin.com/U12Ha1aS
To avoid this, you have to open Bizhawk and start a DS game first. During its emulation you have to set the firmware.bin, after that there won't be any problems
It happens with last commit, but i think this problem exists in all commits (since melonDS was added)

**Comment by SuuperW** [comment]
I renamed my config file, started BizHawk, and set firmware.bin before loading any ROMs, with no issues.

Did you move any files around? The file path in the error message you provided does not match mine. It's looking in [your folder]\BizHawk\melon\tohash.bin whereas mine has an 'output' folder: BizHawk\output\melon\tohash.bin.
If you did not move any files, where did you get your BizHawk build from?

**Comment by Real96** [comment]
I didn't move any files. I got the build from here: https://ci.appveyor.com/project/zeromus/bizhawk-udexo/build/artifacts. I always do a clean install when i download last commit.

**Comment by Real96** [comment]
>  It's looking in [your folder]\BizHawk\melon\tohash.bin whereas mine has an 'output' folder: BizHawk\output\melon\tohash.bin.
melon folder is always generated after i start a ds game, then i set the firmware and everything works

**Comment by SuuperW** [comment]
Ah. Should be fixed now with commit 358f1df.

**Comment by Real96** [comment]
> Ah. Should be fixed now with commit [358f1df](https://github.com/TASVideos/BizHawk/commit/358f1dfd3337cbddc750545cd2215a9af6b74bc4).

Seems to be fixed. Pls check againt this error: https://github.com/TASVideos/BizHawk/issues/1928
You closed it before, but it hasn't been fixed t.t i wrote there what still happens
