### ISSUE TITLE
Documentation Bug - bitnot

### ISSUE THREAD

**Issue by Meerkov** [TASVideos/BizHawk#2015]
http://tasvideos.org/Bizhawk/LuaFunctions.html
At this address, you can go to the bit operations tab ("bit") and see this function

> 
> bit.bnot
> - uint bit.bnot(uint val)
> - Bitwise NOT of 'val' against 'amt'

This isn't correct, as there is no 'amt' input. This was likely a copy paste error from the other bitwise functions.

**Comment by alyosha-tas** [comment]
Fixed

**Comment by YoshiRulz** [comment]
This is very much not fixed. (Also natt put a typo in that commit message.)
https://github.com/TASVideos/BizHawk/blob/4236662f5315eda5f6edf24eb0de3bd7e4db4602/src/BizHawk.Client.Common/lua/LuaHelperLibs/BitLuaLibrary.cs#L28
