### ISSUE TITLE
TAStudio: Loading a tasproj broken in latest commit

### ISSUE THREAD

**Issue by alyosha-tas** [TASVideos/BizHawk#2236]
Can't open any movies. Looked briefly at the latest commit that reboots the core but couldn't see an obvious fix.

**Comment by adelikat** [comment]
This has been fixed for a bit now

**Comment by alyosha-tas** [comment]
I still can't open any movies in TAStudio.

The problem is that _queuedMovie is null when RunQueuedMovie is called in MovieSession.cs

This started in 0925997

**Comment by alyosha-tas** [comment]
Fixed in dev now, thanks!
