### ISSUE TITLE
Starting a new movie recording while a movie is still playing will cause inputs to not be accepted

### ISSUE THREAD

**Issue by Reinc01** [TASVideos/BizHawk#2468]
After recording an input movie is NESHawk, I stop the recording and then go to the "play movie" window. Then I close this window and resume the recording of my input movie from the latest save state. However, games do not respond to my input after aforementioned actions. I always need to play my movie in read-only mode from the second-to-last save state and then make a new savestate to resume recording. This has happened with muliple games.

**Comment by alyosha-tas** [comment]
I looked into this a bit, it doesn't seem to have anything to do with NESHawk in particular.

A movie will not enter record mode until a state is loaded. So if you load a movie from the play movie dialog and have the 'read only' box checked, you will need to uncheck read only and then load a state to resume recording. 

Alternatively if you uncheck the 'read only' box in the play movie dialog window then you can begin recording immediately upon loading a state after the movie loads.

I did find an issue with movie recording though. If you record a movie. Then play back the movie. Then record another movie before that one is finished playing back, the new movie will not accept inputs even though it says you are in record mode.

**Comment by alyosha-tas** [comment]
I fixed this particular issue, so I'll close this one

@Reinc01 if you have further movie issues, please give EXACT repro. steps with no room for ambiguity

**Comment by Reinc01** [comment]
Maybe I did not describe the issue properly, but this still happens in 2.6.1. Moreover, the "ignored" input is still recorded into input movies, which leads to desynchs.
