### ISSUE TITLE
Lua + WinForms + High DPI

### ISSUE THREAD

**Issue by Isotarge** [TASVideos/BizHawk#2604]
ScriptHawk users are starting to complain about the window Lua creates being too small on their 4K screens, with important text being cut off.

<img alt="106403526-c5678d00-63f4-11eb-881a-f3ff9b36e337" src="https://user-images.githubusercontent.com/6367891/106409947-b1be3400-6491-11eb-98f8-e736d02b3c3f.png">

The bug report on ScriptHawk repo is here https://github.com/Isotarge/ScriptHawk/issues/14

We have a root value called ScriptHawk.UI.button_height which scales almost everything on the form dynamically but bumping this value up for high DPI screens still has a number of issues.

![8301f9513213795a6608fa8c6617c775](https://user-images.githubusercontent.com/6367891/106409994-c995b800-6491-11eb-8637-4ce79844ae18.png)

As far as I know, there's currently no way to detect the DPI of the screen that we're running on from Lua.

Would it be feasible for BizHawk to transparently scale up the numbers that get passed to the Lua WinForms bindings based on DPI? Alternatively, could we turn on some flag in the form so that Windows does it for us?

**Comment by YoshiRulz** [comment]
Try messing with this:
https://github.com/TASVideos/BizHawk/blob/fb03771bb7c92f35aa3bcd9af2551be1cc66bf8a/src/BizHawk.Client.EmuHawk/tools/Lua/LuaWinform.Designer.cs#L35-L36

**Comment by Isotarge** [comment]
No luck unfortunately, I tried prodding that enum with all the possible values and the forms are identical, granted I am simulating a high DPI screen with the 200% scaling option in Windows (I don't have a 4K screen to test with).
![ScriptHawk My Machine 200percent scale bugged](https://user-images.githubusercontent.com/6367891/106609066-16be7a80-65b5-11eb-909d-ad5c7efb8cb2.png)

**Comment by ScHlAuChii** [comment]
I ran into a similar problem in 2.6 on my 4K monitor:
![Bizhawk-4K-Bug](https://user-images.githubusercontent.com/12144392/110225332-00257f00-7ee5-11eb-93b9-64a93bd64518.png)

No Record Button - but you can still record by selecting it with the cursor even if its invisible!

**Comment by YoshiRulz** [comment]
@Isotarge New branch for you to try: [`fix-2604`](https://github.com/TASVideos/BizHawk/tree/fix-2604) (and the [pipeline](https://gitlab.com/TASVideos/BizHawk/-/pipelines/273019953/builds)).

**Comment by Isotarge** [comment]
Seems very promising at 200% Windows Scaling setting on my 1440p monitor. Still some minor issues with checkbox labels but that might be on ScriptHawk's end? I'm not 100% sure, would have to look into it. @retrobenny would you be willing to test this build for us on your 4K screen?
![dk641440pscripthawkfix](https://user-images.githubusercontent.com/6367891/111756372-0b67aa00-88ea-11eb-8416-ac0dad8a3312.png)

**Comment by retrobenny** [comment]
I will try to remember to get the build and check how it behaves on my 4K screen some time soon,I already had just turned off my PC and its late into the early morning now before I saw this,I was messing with DK64 physics fixing on 60fps (in PJ64) with promising results and stayed on late.

**Comment by retrobenny** [comment]
...how do I even grab the build on gitlab? >_>

**Comment by retrobenny** [comment]
Seems to be working fine with DK64!

![Bizhawk Scripthawk DK64](https://user-images.githubusercontent.com/16418716/111883728-22aaa400-898b-11eb-810b-fde753fcfaa9.PNG)

**Comment by YoshiRulz** [comment]
> Oh,I had to do something non-obvious and click into the rounded button part for build in pipeline instead of from jobs.

My bad, I forgot the package step is only for `master`.

---

Not sure why checkboxes would be behaving differently. IIRC the box part is drawn inside the padding, so it should use `Height`, which is what the Lua lib sets. I've merged the change anyway.

**Comment by Deakula** [comment]
As far as I can tell, this issue is still present in version 2.9.1


I have a 3 monitor setup in Windows 11. Two of those monitors are set to a resolution of 1920x1080, and the main monitor is set to a resolution of 3840x2160. Regardless of the Windows scale setting for the two 1920x1080 monitors, I observe 3 different behaviors when opening BizHawk on my main 4K monitor:




1. When BizHawk is opened on the 4K monitor and Windows scaling is set to 100%, BizHawk, tools such as TAStudio, and all Lua forms display as expected (albeit too small to be usable with a large 4K display at 100% scaling).
![Scale 100](https://github.com/TASEmulators/BizHawk/assets/21248445/9dbc227b-d6ea-4c74-ad18-4d572523d93e)
![TAStudio 100](https://github.com/TASEmulators/BizHawk/assets/21248445/18e0b738-9d37-436b-a814-4bf63ecd3e6b)


2. When the Windows scaling of the 4K monitor is changed to anything but 100% (eg. 200%) after BizHawk was already opened with Windows scaling set to 100%, BizHawk, tools such as TAStudio, and all Lua forms continue to display correctly (albeit improperly scaled up causing some elements to appear blurry). This is expected behavior as many apps need to be restarted to properly respond to a scale change in Windows.
![Scale 200 after 100](https://github.com/TASEmulators/BizHawk/assets/21248445/e39c020d-a148-4d31-8b01-e26452c1f011)
![TAStudio 200 after 100](https://github.com/TASEmulators/BizHawk/assets/21248445/4435a57f-8e1c-49ed-9f6a-a88318d91184)


4. When BizHawk is opened on the 4K monitor while the scaling is set to anything but 100% (eg. 200%), some BizHawk GUI text (eg. FPS), tools such as TAStudio, and all Lua forms are _**not**_ displayed correctly. Lua forms in particular have incorrect proportions for drawn elements, and elements such as buttons and labels get squished and have their text cut off.
![Scale 200](https://github.com/TASEmulators/BizHawk/assets/21248445/0653c38d-f103-4183-8669-9d87fd2cbe0a)
![TAStudio 200](https://github.com/TASEmulators/BizHawk/assets/21248445/b7287c92-2810-4dda-becb-1f7f06da36af)
