### ISSUE TITLE
Cannot open roms in BizHawk via file association or command line on Windows

### ISSUE THREAD

**Issue by MrCheeze** [TASVideos/BizHawk#2787]
### Summary
The only way I can open a rom right now is by running emuhawk without any arguments and using the Open menu. Other methods that would open the rom directly no longer work.

### Repro
Either
1) doubleclick a file in windows and choose to open in EmuHawk.exe
or
2) Enter something like this in cmd: `C:\Users\Matthew\Documents\Games\BizHawk\EmuHawk.exe "C:\Users\Matthew\Documents\Emulation\ZELOOTD.z64"`

### Output
```
System.NotSupportedException: The given path's format is not supported.
   at System.Security.Permissions.FileIOPermission.EmulateFileIOPermissionChecks(String fullPath)
   at System.Security.Permissions.FileIOPermission.QuickDemand(FileIOPermissionAccess access, String fullPath, Boolean checkForDuplicates, Boolean needFullPath)
   at System.IO.FileInfo.Init(String fileName, Boolean checkHost)
   at BizHawk.Common.PathExtensions.PathExtensions.MakeAbsolute(String path, String cwd)
   at BizHawk.Client.EmuHawk.MainForm..ctor(Config config, IGL gl, Action`1 updateGlobalSound, String[] args, IMovieSession& movieSession)
   at BizHawk.Client.EmuHawk.Program.SubMain(String[] args)
```

### Host env.
- BizHawk 2.6.2; Windows 10

**Comment by YoshiRulz** [comment]
Duplicate of #2747? Please try a dev build.

**Comment by MrCheeze** [comment]
On the dev build, it half-works and half doesn't, but has a different error.

1) Launching via file association / "open with" always gives this error:

```System.UnauthorizedAccessException: Access to the path './ExternalTools' is denied.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.Directory.InternalCreateDirectory(String fullPath, String path, Object dirSecurityObj, Boolean checkHost)
   at System.IO.Directory.InternalCreateDirectoryHelper(String path, Boolean checkHost)
   at BizHawk.Client.EmuHawk.ExternalToolManager.Restart(PathEntryCollection paths)
   at BizHawk.Client.EmuHawk.MainForm..ctor(Config config, IGL gl, Action`1 updateGlobalSound, String[] args, IMovieSession& movieSession)
   at BizHawk.Client.EmuHawk.Program.SubMain(String[] args)
```

2) Launching via cmd works, but for some reason creates an empty "ExternalTools" folder in whatever the current working directory is.

Note that even after doing 2), 1) still fails with the same error.

**Comment by zeromus** [comment]
it would crash because when run by association the working directory is system32 and you cant create directories there. so it's the same problem in both cases, which is simply that ExternalToolManager is trying to create a directory. The code that does that is at least from june 2020, so what may have changed is how the definition of ./ExternalTools works since someone's been mucking around in the path manager code

**Comment by getCursorsExe** [comment]
System32 is the working directory and ExternalToolManager is trying to create it there!? This is dangerous for the computer!

**Comment by YoshiRulz** [comment]
Should be fixed. Also maybe fixed tools annotated `[ExternalToolApplicability.SingleRom]` not being greyed out after opening and then closing the rom.

**Comment by MrCheeze** [comment]
The current dev build has new behaviour, but not fixed just yet.

All failures have the same `Access to the path './ExternalTools' is denied.` message.

* Double-clicking EmuHawk.exe: Fails, unless I manually create a folder named ExternalTools in the Bizhawk folder.
* Opening EmuHawk.exe via searching the start menu: Fails no matter what. (it's probably looking in System32 still)
* Via cmd.exe: Fails, unless I manually create a folder named ExternalTools in the current working directory.
* Double-clicking a rom: Fails, unless I manually create a folder named ExternalTools in the same folder as the rom.
* Double-clicking a rom on a network drive, such as `\\wsl$\Ubuntu\home\matt\git\oot\baserom.z64`: Fails, unless I manually create the ExternalTools folder here. But even if I do that, it still doesn't actually open the rom. It just starts up Bizhawk with no rom loaded.

Looks to me like there's three separate issues here now.
1) That it's looking for ExternalTools anywhere other than in the Bizhawk folder (which doesn't make any sense to me).
2) That even the Bizhawk folder itself doesn't have an ExternalTools folder.
3) The issue with network drives seems to be a different issue, seems like the escaping isn't totally right still.

**Comment by zeromus** [comment]
yep, doubleclicking emuhawk with no .ExternalTools crashes it. I stopped testing there. It's clearly not fixed yet

**Comment by MrCheeze** [comment]
Absolutely everything is working on latest dev build, as far as I can tell 👍

**Comment by JhonatanNizer** [comment]
Hi! Im new using BizHawk. Just downloaded yesterday and I am facing this problem (Version 2.6.2).
Is there any configuration that I need to change ?

I can't open roms via command line but it works fine manually opening selected rom.

**Comment by YoshiRulz** [comment]
Use an older release (2.6.1 maybe?) or a recent [dev build](https://github.com/TASVideos/BizHawk#development-builds).

**Comment by JhonatanNizer** [comment]
Downloaded 2.6.1 and it worked. Thanks! @YoshiRulz
