### ISSUE TITLE
Various UX bugs under Mac OSX

### ISSUE THREAD

**Issue by OmnipotentEntity** [TASVideos/BizHawk#464]
All reported bugs were detected under Yosemite using the most recently distributed compiled version for OSX at time of filing: Version 1.10.0 June 15, 2015

mono --version

```
Mono JIT compiler version 4.0.2 ((detached/c99aa0c Thu Jun 11 18:53:01 EDT 2015)
Copyright (C) 2002-2014 Novell, Inc, Xamarin Inc and Contributors. www.mono-project.com
TLS:           normal
SIGSEGV:       altstack
Notification:  kqueue
Architecture:  x86
Disabled:      none
Misc:          softdebug
LLVM:          yes(3.6.0svn-mono-(detached/a173357)
GC:            sgen
```
1. Clicking menu items sometimes does not work.  Seem to get better results when clicking then unclicking very quickly (button not held down for very long.)
2. Sometimes must click window before menu clicks will work.
3. Sometimes UX is confused whether my mouse is down or up and I am stuck dragging around window.
4. When navigating the control menus, often several empty copies of the menu will spawn, if any of these are dismissed BizHawk will exit.
5. Fonts for messages and counters on screen are illegible.  Appear as blocks.
6. Uncertain if bug or failure to use emulator properly due to other bugs, but when attempting to record an emulator movie, did not record as expected.
7. Shift+F_keys are not accessible on a standard mac keyboard (unsure if a feature of the OS or a failure of detection, but attempting to press Shift+F1 results in simply F1.)
8. F_keys are triggered even when the Fn key is not held down (attempt to adjust screen brightness triggers F1 key).
9. Various common redraw errors (most easily reproduced on the about page and then using the scroll area but they appear pretty much everywhere.)
10. Other issues that cause crashes (SIGABRT) that I haven't been able to determine the cause of.
11. UX is sometimes extremely slow to respond for no discernible reason.
12. Ram Watch and Ram Search seem to be non-functional, have not tested other features.
13. Does not quit when quit is selected from the menu (grays out quit after selecting, does not exit until Window is closed.)

**Comment by Sappharad** [comment]
Thanks for putting this in. Several of them, (especially the menu based ones) are because the native menus are not completely implemented. They work just enough to be able to use them, but never update, for example. I don't know if I'll bother to fix them, the entire UI needs to be replaced. 

I've never had problems with quit before, but maybe that is new then.

**Comment by OmnipotentEntity** [comment]
After SDGQ, I'll be able to upload a video that might help with troubleshooting or narrowing down the issue.  But unfortunately, due to my streaming settings, I didn't capture many of the subwindows that exhibited the problems.  Sorry.

**Comment by Sappharad** [comment]
Ok, here's a complete list of responses on these. I didn't have time to elaborate earlier since I was replying from my phone. On a side note, 1.10.0 is not the latest, 1.11.0 is, but you'd have to had downloaded it from the link in the forum thread because SourceForge hasn't been accepting new uploads for around a week or so now. They had some kind of major failure recently. I just checked again and they're still not accepting new uploads, even though the upload page is available again.

Forum thread where I always keep a link to the latest OS X version:
http://tasvideos.org/forum/viewtopic.php?t=12659

All of the problems you saw probably exist in 1.11.0 though, because I haven't made any OS X specific changes recently. In general, pretty much all of these issues will end up being irrelevant at some point because the current solution is just a wrapper around the Windows UI and I want it to go away and be replaced with a brand new one. (Which is a very early work-in progress.)

My general goal for the current OS X port is just to have something that you can play games with, in addition to playing back TAS input files. (You can record them too, but I've never tested any of the advanced tools around it, outside of basic recording and playback.) It's usable to the point where you can configure firmware, open a rom, play it, etc. The tool windows and dialogs are untouched Windows Forms, some of which aren't entirely compatible with Mono. I've played with a few of them to make them work, but not a lot. 

When the new UI is ready, the only thing it's going to be good for at first is playing games. At that time, I'll probably start releasing 2 OS X builds for a while, one with the new UI which is native and doesn't have a lot of features yet, and the other being the Windows Forms UI, without any of the Mac stuff wrapped around it like I have now. The one will be more awkward to use, but since it won't have native menus and dialogs it will function a bit better. (And be ugly.)

1. Known issue. The way BizHawk handles it's UI is the opposite of nearly every application in existence. In most applications, the UI takes priority over the rest of the application. Any work that occurs is done because a UI action caused it to occur, otherwise work is done in the background so that the UI remains responsive. BizHawk works the opposite way, the emulator has control over everything, including telling the UI when it is allowed to update. Unfortunately, I can't do this on OS X, so I crudely reversed the process back to the way it's supposed to be and the UI once again takes priority and tells the emulator when it's allowed to do work. But that work still isn't done in the background, and BizHawk is given lots of time to make sure it can run full speed, which lowers the responsiveness of the native menus. The problem is worse on older machines, on my newest one it doesn't really happen but my primary machine is 7 years old and it does happen there.

A lot of the UI lag is caused for this same reason. There may be some ways I can improve it further, but I don't think it's 100% solvable as long as I want to mix native OS X menus and dialogs with WinForms. The mono folks basically told me a few years ago on IRC that it was not possible, and I did it anyway.

2. Haven't seen this, but I believe you. See 1 above for reason. I've had the file open dialog sometimes pop open in the background and I had to click something else then click back to be able to use it.

3. Same reason as 1.

4. Not sure what this means.

5. Screenshot would be helpful. I don't recall ever seeing blocks anywhere, but I know a few of the toolbar images don't look correct. Those are a mono-specific problem, but I can usually fix them.

6. Is this an input recording, or a video file? Input recordings should work, I've done that before. But video recording does not. I seem to recall looking at it at one point in time, but I don't remember at the moment if there was something preventing it from working. I believe it uses an external tool for encoding video, and usually that requires me to bundle said tool with the application.

7 and 8. I'm not surprised, I've never used those keys before. Might be fixable, I can look into it since the same input code will be used in the new UI as well.

9. This is a mono WinForms problem, I can't do much about it. The solution is for me to make a new UI that is native.

10. If it's easily reproducible, let me know. I don't get any crashes just playing games, but certain untested tools and features could probably end up crashing just because I've never tried them to find problems to fix.

11. See 1 above for reason.

12. I can take a look, but if it's something that requires Windows-specific code to work, I may just have to disable it altogether. (Unless I write a replacement) One of the reasons Lua isn't supported in the OS X build is because of stuff like this, where it's not trivial to replace and I prefer to spend time fixing stuff that I want to use.

13. I can reproduce this in 1.11.0. I will fix it. In the meantime, just click the close box.

**Comment by Sappharad** [comment]
1, 2, 3 and 11 are probably fixed by 5f645949d73dcc39f8f558db3c3dd1ea9005bb1b. I still need to do some testing on other machines, but it's significantly better now, and I think it almost always behaves correctly now.

13 is fixed by bf589f63ce08b8450e846251a7a4dac13da811ab.

You didn't report this one, but the menus would never update when you did stuff. (For example, when you opened a game it wouldn't show up in the recent list until the next time you ran BizHawk, if you changed one of the menu options with a checkbox it wouldn't update.) This was something I never finished because I couldn't do it the same way as Windows, (which tries to update menus every time you open them) but I came up with a work-around that seems to work for every situation I'm aware of. That is fixed in bf589f63ce08b8450e846251a7a4dac13da811ab.

The fixes I just mentioned will be in the OS X build of 1.11.1, which I will probably post tomorrow.

**Comment by parasyte** [comment]
Just tested 1.11.1. I'm still having the same issues that I experienced last year: http://tasvideos.org/forum/viewtopic.php?p=387808#387808

Show-stoppers and deal-breakers:

* Controller inputs are not working
* Screen flashes on/off every frame

**Comment by Sappharad** [comment]
When you say controller inputs, do you mean with a controller? Controllers aren't implemented yet on for OS X, you must use a keyboard.

I don't have any screen problems so I'm not sure what you mean by that. I've tested on my Mac Pro (2008 model), a 2010 MacBook Pro, and a 2015 MacBook Pro. Video output is fine on all 3. Is there anything special about your setup that might help me reproduce the flashing you describe?

I've been bitten by the archive problem too, I should probably just fix that. The 3rd party library used to scan a file to decide if it's an archive sucks and decides that lots of files are archives when they aren't.

**Comment by parasyte** [comment]
I mean keyboard, for controller input. The default keyboard layout is invalid for OS X. It must be configured and saved, then it works!

The screen flashes occur inconsistently. It's like the emulator gets out of sync with the hardware video refresh rate. I've after been unable to reproduce it, the more I try. If I could find where the preferences are stored, I'd delete it all and see if it's an issue that is resolved by caching ... something.

**Comment by Sappharad** [comment]
I've updated the default keyboard layout for the next release. Wasn't planning on it, (the new UI had correct defaults already) but since we're stuck with the old UI for the near future, I guess throwing it in won't hurt.

The config is in BizHawk.App/Contents/MacOS/MonoBundle/config.ini but I don't think deleting it is going to change anything. Do you happen to be running at a refresh rate other than 60hz? The UI is basically on a timer that fires every 60th of a second, telling the emulator to run for the next frame. It used to be 120, but I reduced it to 60 to fix UI responsiveness in the last release. The whole timer thing was unavoidable for reasons I mentioned earlier on this page, as long as I'm mixing native and WinForms together.

**Comment by parasyte** [comment]
Pretty sure I'm running at 60Hz. Although it could be something crazy like a non-integer refresh rate.

**Comment by Sappharad** [comment]
Going to close this, since the remaining issues won't be fixed.

Starting with 2.0, BizHawk went 64-bit only. The WinForms implementation on macOS does not support 64-bit and Mono will not be getting support for it in the future, so I can't wrap the existing Windows UI anymore.

Moving forward a brand new UI has to built to continue supporting macOS. That's slowly a work-in-progress. Unfortunately, I'm also blocked on that too, because of a linker bug that I've reported to Microsoft which they have yet do anything with. It doesn't block me from working on the new UI, but it does block me from making 64-bit builds. Any news about updates can be found in forum thread about OS X builds. There probably won't be any news in the near future.
