### ISSUE TITLE
Master System: Micro Machines (E) doesn't work

### ISSUE THREAD

**Issue by Reinc01** [TASVideos/BizHawk#684]
When I try to launch SMS Micro Machines (E) on Bizhawk I just get violet screen.

**Comment by hegyak** [comment]
Confirmed Good Hash:
SHA1:425621F350D011FD021850238C6DE9999625FD69

**Comment by alyosha-tas** [comment]
Fixed with commit to choose correct mapper

**Comment by Reinc01** [comment]
I just checked, and it still doesn't work. Are you sure you are not referring to fixing the NES Micro Machines emulation instead?

**Comment by hegyak** [comment]
I checked this against the latest Interim Build.  Still a Purple/Violet Screen for the SMS version of the game.

**Comment by alyosha-tas** [comment]
works fine for me:

A90CF8D68FA8B1F0BA00F0DDB9D547B7		Micro Machines (E)	SMS

http://i1053.photobucket.com/albums/s468/daviomace/micro_zpswhvzxldl.png

Oh I see, different Hash. Let me add that one too.

**Comment by hegyak** [comment]
The No-Intro SHA-1 ROM hash is:
425621F350D011FD021850238C6DE9999625FD69

**Comment by hegyak** [comment]
Resolved with:
https://github.com/TASVideos/BizHawk/commit/d6d2e4c6f9d13c83bf85cd7c1e24f69ce80450d1

Thank you to alyosha-tas for getting the Mapper Data for the other hash setup.
