### ISSUE TITLE
Bizhawk Mupen64plus core breakpoints aren't running

### ISSUE THREAD

**Issue by ProbablyButter** [TASVideos/BizHawk#872]
Ever since BizHawk 1.12.1, breakpoints inside BizHawk and from the Lua interface have stopped working in the Mupen64plus core.

I believe this is due to switching to the built-in mupen64plus debugger which is supposed to be faster.

However, I suspect that the debugger wasn't enabled in the mupen64plus core itself (in the standard mupen64plus there's a config flag **EnableDebugger**, but I don't know how to set this in BizHawk), and without this enabled any breakpoints added to the mupen64plus core are not caught.

Going back to version 1.12.0 and the breakpoints do work (albeit, very slowly due to internal BizHawk breakpoint handling).

**Comment by ProbablyButter** [comment]
A very simple script to test if breakpoints works: (this is on OoT 1.0):

https://pastebin.com/kbLDzfXp

**Comment by vadosnaprimer** [comment]
It keeps haunting me. See what problems I was having when the needed flag was set:
https://github.com/TASVideos/BizHawk/commit/19cf3b8551ade0fd1e5dd96d1ee2cc580d858992

I dunno how to resolve it. @Wyst3r?

**Comment by vadosnaprimer** [comment]
Reverted my ill-fix, this one is fixed in https://github.com/TASVideos/BizHawk/commit/77fa17ccddc5efa2bf0433b8d2feb8b7190b2483

**Comment by Wyst3r** [comment]
Still not working. There seems to be an unresolved merge conflict in mupen64plus-core.vcxproj. Though the main issue now is that the DBG definition needs to be added to the x64 project settings (it's only in Win32 atm).

@vadosnaprimer

**Comment by vadosnaprimer** [comment]
It works if all you do is just adding that flag to x64 project settings?

**Comment by Wyst3r** [comment]
Yes. I can't compile BizHawk atm because I don't have the proper Visual Studio version, but when I compiled mupen64plus with DBG added to x64 settings and replaced the dll in my 2.1.0 release folder, it worked.

**Comment by vadosnaprimer** [comment]
@Wyst3r, pushed, test please.

**Comment by Wyst3r** [comment]
The new .dll works, thanks :)

Side note: I noticed the merge conflict was resolved by keeping the line with DBG in it, but the removed line had newer versions of most library dependencies. For example it's now referencing SDL 1.2.14 which no longer exists in the win32-deps folder (it's 1.2.15 now).

**Comment by vadosnaprimer** [comment]
It's win32 target that no longer makes sense, so I won't have to rebuild, but I'll restore the new deps reference.
